### ISSUE TITLE
Cant start app from game library

### ISSUE THREAD

**Issue by aranwarez** [LightningMods/etaHEN#1]
Application cant be started from game library but only from home screen. Certain application like custom internet browser enabler

**Comment by LightningMods** [comment]
Hello, are you available to test a fix?

**Comment by aranwarez** [comment]
Sure. Also, i found that after resuming ps5 from rest mode, ps5 becomes very slow, ETAHEN crashed if used fliprate enabler using button combination Square+Traingle.. I thought its beta and you were already aware about that,so i didnt create another issue for it.

**Comment by LightningMods** [comment]
here's 2 new payloads to try, let me know if it works both issues for you
[payloads.zip](https://github.com/LightningMods/etaHEN/files/13199990/payloads.zip)

**Comment by aranwarez** [comment]
Sorry for late reply, Here is report of my test.
For etaHENwithcheats..
1. FPKG games runs fine from game library .. Its just internet brower application that doesnt start. Its not even a real app just url link in app.db so i think we can ignore it.
2. ETAHEN didn't crash after enabling fliprate this time..  And  illusion libhacker patchs ran as expected for both fpkg and retail pkg.. But if you turn fliprate off and on again etaHEN will crash and illusion libhacker patches doesnt work from there..
3. After resuming from rest mode, ps5 isn't slow anymore...

For etaHEN
1. Button combination for Fliprate doesn't work. Illusion libhacker patches doesn't work even for retail games..

**Comment by LightningMods** [comment]
Hello, the cheats might be hit or miss for now until we get done with a cheats manager, as for the success rate other than kernel panics I've had an 100% success rate launching the payload personally, other than that it looks like 2/3 of the reported issues have been fixed which is what I was after, besides the issues with cheats are you liking the Payload so far?

**Comment by aranwarez** [comment]
The new payload is far better than 1.0b .. There are some minor issues with enabling/disabling fliprate and pathces/cheats but overall im having good experience..

**Comment by LightningMods** [comment]
That good to hear, etaHEN 1.1b has been released publicly now
