### ISSUE TITLE
Game dumping: inf%

### ISSUE THREAD

**Issue by pquerner** [LightningMods/etaHEN#10]
Hey,

sometimes the progress is shown as "inf%" instead of actual % progress (number).
I saw process was done with 1.x% and afterwards (so far) only "inf%".

Its a PS4 PSN game (still activated) installed on M2.

// edit it worked at the second try (after console restart)

// edit2
now I am over 100% status. x)

**Comment by LightningMods** [comment]
hello, I will see whats causing this bugs soon

**Comment by LightningMods** [comment]
Update on this issue, we are moving towards a new dumper, see it here
https://vxtwitter.com/LightningMods_/status/1776655422381834467

**Comment by LightningMods** [comment]
this no longer happens with the new dumper and is now outdated
