### ISSUE TITLE
rest mode second time freeze 

### ISSUE THREAD

**Issue by jonesmith518** [LightningMods/etaHEN#13]
hey guys, come out of rest mode twice and 
[etaHEN.log](https://github.com/LightningMods/etaHEN/files/14965092/etaHEN.log)
screen freezes, here is the log
ps5 version 4.50

**Comment by LightningMods** [comment]
if this still happens re-open the issue but it should be fix in the new release with the added rest mode menu
![image](https://github.com/user-attachments/assets/10d34947-8381-4e14-b803-05c03910fb92)
