### ISSUE TITLE
Debug settings options

### ISSUE THREAD

**Issue by pixeltester** [LightningMods/etaHEN#16]
Thank you for the new 1.8 release. As far as I understand it the debug settings menu is fully replaced and the original options are inaccessible unless you add them, is that correct? If so please could you expose the external hdd options from the original debug settings menu in the next release? Since I connect and remove usb drives quite often I have habitually used the unmount option from there rather than just pull them out.

**Comment by LightningMods** [comment]
Sure, I can add anything from debug settings to the toolbox like how I added the Blu-ray license activation in the utilities menu

**Comment by LightningMods** [comment]
to confirm this is the menu you want right?
![My Great Game - My Great Capture_2024-08-13_16-19-03](https://github.com/user-attachments/assets/e712ce34-0810-4b6d-a25e-bedee9930950)

![My Great Game - My Great Capture_2024-08-13_16-19-08](https://github.com/user-attachments/assets/6dfec9c5-f3e2-4ebd-9937-319af22e72fa)

**Comment by pixeltester** [comment]
That's the one, thank you for very much for adding it.

**Comment by jackfavvv** [comment]
Yes, this will be really helpful, since the PS5 will tell you to format the drive when trying to unmount the normal way.

**Comment by LightningMods** [comment]
hello this feature is included in the newly released etaHEN 1.9B and so this issue is now closed
