### ISSUE TITLE
EtaHEN 1.8B: Error loading XML patches (itemzflow) and Failed elfldr plugin

### ISSUE THREAD

**Issue by arantis3** [LightningMods/etaHEN#17]
Everytime I try to load xml patch on Itemzflow, I get this error:
![_IqXIEd-](https://github.com/user-attachments/assets/62a3b5bf-652d-42db-80e9-123339a80e85)

I don't know if it has any relation with elfldr, but when I try to activate/deactivate the plugin I get the following error:
![ADovwuWy](https://github.com/user-attachments/assets/a324412e-8e6f-4d9f-9e23-e497b785d5ce)

I remember starting an older version of etahen by mistake and rebooting again at 1.8b. Some kind of file conflict? 
How can I fix it? Thanks!

**Comment by LightningMods** [comment]
try deleting itemzflow and the illusion cheats plugin then reinstall itemzflow or you can update the cheats plugin manually via https://github.com/LightningMods/etaHEN-SDK/actions/runs/10360069201/artifacts/1804012616

**Comment by arantis3** [comment]
Thanks for your effort and help! I deleted the itemzflow app from the PS5 menu and also deleted the "data>etaHEN" and "data>Itemzflow" folders using FTP. I don't know if I need to delete anything else. I did a clean load of etaHEN and a clean install of itemzflow. I put my xml patch inside the "data>etaHEN>patches>xml" folder. Itemzflow recognizes it, I activate it but this time when the game starts no debug notification appears. No game starts the patches. I tried deleting the illusion plugin and replacing it with the one you gave me and the same thing happens.

So I've been doing different tests: I've edited the "0" value and changed it to "1" from the "0xXXXXXXX...txt" files located in etaHEN>patches>settings. Now the games load with the message "X Patches applied", but none of those patches work for me. 

So at this point I don't know if...

1- the error is in manually editing the file (it should have loaded the patches automatically?) 
or...
2- if the error is in the patches itselves that don't work for the game (Something strange because I'm testing the unlock all patch for Call of Duty Cold War, which works according to [https://x.com/zombie_round/status/1809272137582059608](url) )

Sorry for all this mess. But I'm getting to a point where I'm pretty confused about why the patches aren't working for me without editing the files. Thanks for everything you do for the community!

**Comment by kokotas89** [comment]
Have you checked itemzflow_app.log file? I've been trying to get the patches to work for two days without success as well. Inside that file it says "The requested patch doesn't match the games update version".

**Comment by 2600box** [comment]
> Have you checked itemzflow_app.log file? I've been trying to get the patches to work for two days without success as well. Inside that file it says "The requested patch doesn't match the games update version".

That is the error I see too with titles like Bloodborne, which worked fine at 60fps using 1.7b

**Comment by kokotas89** [comment]
> > Have you checked itemzflow_app.log file? I've been trying to get the patches to work for two days without success as well. Inside that file it says "The requested patch doesn't match the games update version".
> 
> That is the error I see too with titles like Bloodborne, which worked fine at 60fps using 1.7b

Well I got it working after trying different versions of bloodborne. (I own the original game pal version) When you have to correct version of the game installed, you need to go to itemflowz, open game menu, and go to trainers. If everything is correct then it will download and show all available patches there. You can enable them by pressing x on each one.

**Comment by arantis3** [comment]
I've found the solution for my case. I've edited the xml file by shortening certain texts like the name of the patch or the creators and surprisingly, now the patches load automatically. Thanks everyone! 

By the way, do you also experience kernel crashes on the PS5 after turning it off in etaHEN 1.8b? My installation is clean and I have everything disabled (plugins too).

**Comment by LightningMods** [comment]
@arantis3 im glad you solved your issue, also if you want you can join the PKG-Zone discord and test out the brand new Lite mode, just join and tell us you are there to test
https://discord.gg/U5ZP6K75

I am now closing this issue since it was resolved
