### ISSUE TITLE
Issues getting some 60fps patches to work with Itemzflow

### ISSUE THREAD

**Issue by jackfavvv** [LightningMods/etaHEN#19]
Hello LightningMods,

After trying the new etaHEN 1.8B, I noticed that some patches work, and some have this issue:
![Itemzflow Game Manager (PS5)_20240822031715](https://github.com/user-attachments/assets/d105353b-8693-4e67-9821-48d752095a37)
Tried to update the patch database to see if it would resolve the issue, but the Triangle button was also glitched out.  
It might be due to illusion0001's newer patch format that uses Type="mask" instead of Type="bytes", but I'm not 100% certain.

Thanks.

**Comment by LightningMods** [comment]
Hello, that is correct right now the mask type is among the things not supported but ill fix some of the other issues

**Comment by jackfavvv** [comment]
I had a feeling, since the newer "mask" types gave me issues as well outside of etaHEN. But I have no doubts that further support will be available in future releases, once etaHEN 1.8b & Toolbox is past its experimental phase.
