### ISSUE TITLE
Support for 1.x and 2.x PS5-UMTX-Jailbreak

### ISSUE THREAD

**Issue by Cr0wTom** [LightningMods/etaHEN#21]
Any plans for support for 1.x and 2.x?

**Comment by LightningMods** [comment]
we will see if kstuff gets ported but I'm not sure if there's enough people to benefit from a port for 1.xx and 2.xx

**Comment by LightningMods** [comment]
hello this feature is included in the newly released etaHEN 1.9B and so this issue is now closed
