### ISSUE TITLE
Etahen works (debug enabled, install itemzflow pkg, browser) but itemzflow keeps waiting for etahen (30s) ?

### ISSUE THREAD

**Issue by broke23** [LightningMods/etaHEN#6]
PS5 FW 4.50 here

sorry if I'm at the wrong place, to me it seems right over here...

I tried modded warfare's instructions, but then residing on raspberry pi3b (so using idlesauces JB process at first) 

I get the page and all that, jb is ok, but when loading etahen (latest 1.4b) : debug settings are ok, can install itemzflow, but when trying to open itemzflow, it's waiting for etahen 30s and then says no go ... so every time I ty etaHen (1.4b) it tries opening etaHen, but then says "payload exited" though debu is enabled, the popup at the side never comes saying it's up and running ... so it's partially working, letting me install packages yes, but not opening them when it requires etaHen...

I once arrived with ftp to remove the etahen config file, didn't solve a thing ...  Ended up resetting ps5 again, started from scratch, stuck again, tried with es7....(afterwards  even Zecoxao... wolf... those are the same where you can load etahen directly it seems) jb itsself seems ok, but never can i get itemzflow up and running (stuck asking 30s etahen)

anyone care to help or wrong entry here ? :)

**Comment by LightningMods** [comment]
Try with the new etaHEN update and tell me if the issue continues
https://github.com/LightningMods/etaHEN/releases/tag/1.5b

**Comment by broke23** [comment]
Problem coexists. With newer version. 

No pop up and "payload exited" mentioning right hand side.

Anyway I can get you guys some logs anywhere yet as ftp seems to be working from time to time?

**Comment by broke23** [comment]
Sorry wrong button

**Comment by LightningMods** [comment]
that sounds like an issue with your host but you can send me the logs in /data/etaHEN

**Comment by broke23** [comment]
I'll double check that folder but ftp'ing there to see and remove config never shows anything apart from very first time?!

**Comment by LightningMods** [comment]
etaHEN 1.5B creates /data/etaHEN/etaHEN.log everytime it launches so you should at least have that

**Comment by broke23** [comment]
Ah great to hear I rally hope to find something there then!

**Comment by LightningMods** [comment]
I'll close this ticket in 48 hours if I don't hear back

**Comment by broke23** [comment]
Hope to come back with feedback today.  Couldn't even access ftp no more so reinstalling Ps5 completely and start over.

**Comment by broke23** [comment]
Reinstall did the trick. After a few times JB passed and from 1st time etaHen loaded up. I hope it sticks now. Thanks 👍
