### ISSUE TITLE
Critical ETAHen 1.5b Debug notification bug after launching PS5 dumps

### ISSUE THREAD

**Issue by edmaren** [LightningMods/etaHEN#7]
ETAHen 1.5b with cheats enabled in Firmware 4.50 shows an infinite loop debug notification after launching any PPSA dump: "get_app_info(PPSAwhatevergame) failed! -1" and doesn't end until the game is closed, hiding 1/3 of the screen. Game runs but is impossible to play. Thank you.

**Comment by LightningMods** [comment]
I never tried the cheats with PPSA games but I can remove that notifcation

**Comment by LightningMods** [comment]
Hello, I updated the payload to fix that issue, let me know if your issue is resolved
https://github.com/LightningMods/etaHEN/commit/e75eca408de91503b2e2e2482d03e4f6cadeed31

**Comment by edmaren** [comment]
Thank you, it's fixed. Sorry to ask you in this comment, but now that we finally can load PS5 dumps and PS4 patches in the same session, would it be possible to load a custom libhijacker bin? I guess this could only happen as a payload after loading etaHEN (maybe, in the same folder, naming the custom bin in a certain way), so you could send custom patches like what games are launched with 120hz by default (without changing PS5 video options), patches for fpkg version vs disc (The last guardian) or selecting what options are applied (illusion has restored motion blur and chromatic aberration defaults in Bloodborne with the last update, that I personally don't like). Thank you so much for your work.

**Comment by LightningMods** [comment]
It would be a better idea just to add cheats to Itemzflow
