### ISSUE TITLE
etaHEN 1.5b rest mode not working

### ISSUE THREAD

**Issue by pixeltester** [LightningMods/etaHEN#8]
This is bug report regarding etaHEN 1.5b on a 4.03 PS5. I've entered rest mode a couple of times and the PS5 shows the entering rest mode screen and turns off but then the light on the console just pulses indefinitely and I'm unable to wake it from rest mode, the only option is to force power off. I've had no issues at all with rest mode in the past few versions so this seems to be a new bug.

**Comment by LightningMods** [comment]
tell me if this issue still happens with the newest payload, I tested this myself and I was able to come out of rest mode twice so im not sure why your PS5 wouldnt unless you just got unlucky 
https://github.com/LightningMods/etaHEN/commit/e75eca408de91503b2e2e2482d03e4f6cadeed31

**Comment by pixeltester** [comment]
Looks good now, I'm not getting the issue with the newest payload.
