### ISSUE TITLE
etaHEN v1.4 and v1.5 not working on 4.02 console

### ISSUE THREAD

**Issue by baybarsturan** [LightningMods/etaHEN#9]
In version 4.02, when sending etaHEN v1.4 and v1.5 payloads via Netcat from the Specter Host page on es7in1.site, the console closes immediately. Likewise, when the etaHEN button is pressed on other host pages, the console also closes. I mentioned this issue on the Discord server last night. I just wanted to summarize the problem here as well.

**Comment by LightningMods** [comment]
I checked the offsets for etaHEN for 4.02 and they all seem right when compared with kstuff and libhijacker cheats, further testing required by someone on 4.02

**Comment by LightningMods** [comment]
Hello, this payload should fixed for 4.02, let me know if it works for you too
[etaHEN-test.zip](https://github.com/LightningMods/etaHEN/files/14226105/etaHEN-test.zip)

**Comment by baybarsturan** [comment]
it is working now. Thanks again.
